---
title: "test"
author: "Yifan Zhu"
date: "2/11/2023"
output: html_document
---

 
```{r, message=FALSE, warning=FALSE, include=FALSE}
# set global 
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)


# These are the packages you will need for this activity.
packages_needed <- c("tidyverse", "dplyr", "tidyr", "tibble", 
                     "UpSetR", "naniar", "GGally",
                     "plotly", "ggplot2", "kableExtra", "formattable", "ggpubr",
                     "usmap", "nnet", "ggridges", "effects")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE, 
      repos = "https://cloud.r-project.org/")
    }
  }
)

# basic libraries
library(tidyverse)
library(dplyr)
library(tidyr)

# Others
library(tibble)
library(UpSetR)
library(naniar)

# visualization libraries
library(plotly)
library(ggplot2)
library(ggpubr)
library(kableExtra)
library(usmap)
library(nnet)
library(ggridges)
library(effects)
library(formattable)
library(hrbrthemes)
library(GGally)
library(viridis)

```

```{r}
df <- read.csv("/Users/yvonne_zhu/Desktop/forR.csv")

s2 <- df %>%
  filter(seriousness == 2)

df1 <- df %>%
  select(seriousness, patientsex, patientonsetage,reaction_count,drug_count)

df$seriousness <- as.factor(df$seriousness)
df$patientsex <- as.factor(df$patientsex)
```


```{r}
# for testing 
library(brms)
model <- brm(seriousness ~ patientonsetage+reaction_count+drug_count+patientsex,
             data=df, family=bernoulli(), seed=2020, control=list(adapt_delta=0.90))
```

```{r}
summary(model)

```


### for visualization 
```{r}
full <- read.csv("/Users/yvonne_zhu/Desktop/full_dataset.csv")

```

```{r}
ggplot(df, aes(x=reaction_count, color=patientsex)) +
  geom_histogram(fill="white", position="dodge",bins=30)+
  theme(legend.position="top")+
  scale_color_manual(values=c("#92B1B6", "#CED2C2","#F2C75C"))+
  theme_minimal()

```
```{r}
ggplot(data = full, aes(x = reaction_count)) + geom_histogram(binwidth = 20)+ facet_wrap(~seriousness)
```


```{r}
ggplot(df, aes(x=reaction_count, color=patientsex, fill=patientsex))+ 
  geom_density(position="identity", alpha=0.5)+
  scale_x_continuous(limits = c(0, 40))+
  facet_grid(patientsex ~ .)+
  scale_fill_manual(values = c("#92B1B6", "#CED2C2","#F2C75C"))+ 
  scale_color_manual(values = c("#92B1B6", "#CED2C2","#F2C75C"))+ 
  labs(caption="Source: FDA’s Adverse Drug Events database, retrived Feb.11, 2023", x="reaction count", y = "number")+ 
  theme_minimal()
```


```{r}
drug <- read.csv("/Users/yvonne_zhu/Desktop/Drug.csv")

over <- drug %>%
  filter(X0 > 132) %>%
  arrange(X, decreasing = TRUE) 

below <- drug %>%
  filter(X <= 132)

merged <- over %>%
  add_row(X=13, index="OTHERS", X0=sum(below$X0))
```

```{r}
ggplot(data=over, aes(x = reorder(f.index, -X0), y = X0)) +
  geom_bar(stat="identity", fill="#92B1B6")+
  geom_text(aes(label=X0), vjust=-0.3, size=3.5)+
  theme_minimal()+
  labs(caption="Source: FDA’s Adverse Drug Events database, retrived Feb.11, 2023", x="drug", y = "frequency")+ 
  theme_minimal()

```

```{r}
count <- full %>%
  group_by(patientsex, seriousness) %>%
  count()

count <- count %>%
  drop_na() 
```

$$ logit(P_i)=ln(P_i/(1-P_i)) = \beta_0+\beta_1  PatientAge_i + \beta_2 Pateint Male + \beta_3 Patient Female +\beta_4 Reaction Count + \beta_5 Drug Count$$

```{r}

ggplot(df, aes(x=reaction_count, color=patientsex)) +
  geom_histogram(fill="white", position="dodge",bins=30)+
  theme(legend.position="top")+
  scale_color_manual(values=c("#92B1B6", "#CED2C2","#F2C75C"))+
  theme_minimal()

```


```{r}
cleaned <- full %>%
  filter(patientonsetage <150)

ggplot(cleaned, aes(patientonsetage, reaction_count)) +
  geom_point(aes(color=patientsex))+
  theme_minimal()

```